version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_api_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npm run migration:run && node dist/main.js"

  db:
    image: postgres:16-alpine
    container_name: pg_db_prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data_prod:
